services:

  backend:
    build: .
    ports: 
    - "8000:8000"
    volumes:
      - .:/app                      # live code reload without rebuilding
      - ./chroma_db:/app/chroma_db  # persist vector store across restarts
      -  ./data:/app/data           # persist uploaded documents

    env_file:
      - path: .env

  frontend:
    build: ./app/frontend
    ports:
      - "8080:8080"
    volumes: 
      - ./app/frontend:/app              # live code reload without rebuilding
      - /app/node_modules              # dont overwrite node_modules within container
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
